y1 = int(input()); m1 = int(input()); d1 = int(input())
y2 = int(input()); m2 = int(input()); d2 = int(input())
a = (y1, m1, d1); b = (y2, m2, d2)
if a < b: print(1)
elif a > b: print(2)
else: print(0)
